adding the image to the donation view as an image
paintedbirds/hoydonamos-api pull request #15
Opened 2022-01-30 16:19 UTC by alejandroGonGon

About :

This Pull Request add an image to the Donation View in the Admin Panel, insted of being an URL to be clicked there is an Image in the information.

Extra :

I also add the same logic to the User section in the Donation View.

Demo: 
![image](https://user-images.githubusercontent.com/56725406/151707761-7c791852-d3b3-4b42-8004-b7a4fbc81656.png)
![image](https://user-images.githubusercontent.com/56725406/151707792-3c4d3803-91c8-4cac-8ca0-a5c9959156d9.png)

2022-01-30 16:19 UTC, LautaroPardo0210 commented
Task linked: [CU-1tkgbhf Show donation image URL as clickable](https://app.clickup.com/t/1tkgbhf)

2022-01-30 16:27 UTC, rubenderigo commented on app/Orchid/Screens/DonationEditScreen.php
> +                          alt='sample'
alt atribute could be about the picture?

2022-01-30 16:27 UTC, rubenderigo commented on app/Orchid/Screens/DonationEditScreen.php
> +                          alt='sample'
same the other

2022-01-30 19:18 UTC, rubenderigo approved these changes

2022-01-30 19:18 UTC, rubenderigo commented on app/Orchid/Screens/DonationEditScreen.php
> +                          alt='image-donation'
is not necessary add "image" because the alt attribute belong to img etiquette (is redundant)

2022-01-31 00:07 UTC, rubenderigo requested changes
missing alt attribute

2022-01-31 00:20 UTC, rubenderigo approved these changes
LGTM

2022-01-31 00:28 UTC, merged