New way to Handle the errors.
paintedbirds/hoydonamos-api pull request #17
Opened 2022-02-23 01:30 UTC by alejandroGonGon

### Changes in the code:
Added the FormRequest to the instances where the Validation is used to handle the errors, being more indiviudal and easy to change and add rules to the attributes.

### Attachments
![image](https://user-images.githubusercontent.com/56725406/155247609-94bbcc54-c543-4fa6-943d-323c3f001ece.png)

### Documentation
[Form Request Laravel](https://laravel.com/docs/5.7/validation#form-request-validation)

2022-02-23 11:41 UTC, rubenderigo approved these changes

2022-02-23 11:41 UTC, rubenderigo commented on app/Http/Requests/PetitionStoreFormRequest.php
> +            'description.required' => 'La descripcion es requerida',
```suggestion
            'description.required' => 'La descripción es requerida',
```

2022-02-23 11:41 UTC, rubenderigo commented on app/Http/Requests/StoreDonationFormRequest.php
> +            'description.required' => 'El campo de Descripcion es requerido',
```suggestion
            'description.required' => 'El campo de Descripción es requerido',
```

2022-02-23 11:41 UTC, rubenderigo commented on app/Http/Requests/StoreDonationFormRequest.php
> +            'image.max' => 'El maximo de la imagen es de 5Mb',
```suggestion
            'image.max' => 'El máximo de la imagen es de 5Mb',
```

2022-02-23 11:41 UTC, rubenderigo commented on app/Http/Requests/UpdateFormRequest.php
> +            'phone.numeric' => 'Porfavor indique un numero',
```suggestion
            'phone.numeric' => 'Por favor indique un número',
```

2022-02-23 11:41 UTC, rubenderigo commented on app/Http/Requests/UpdateFormRequest.php
> +            'about_me.string' => 'Porfavor indique solo texto',
```suggestion
            'about_me.string' => 'Por favor indique solo texto',
```

2022-02-23 11:41 UTC, rubenderigo commented on app/Http/Requests/UpdateFormRequest.php
> +            'image.max' => 'El maximo de la imagen es de 1Mb',
```suggestion
            'image.max' => 'El máximo de la imagen es de 1Mb',
```

2022-02-23 13:50 UTC, nicocadq approved these changes

2022-02-23 13:50 UTC, nicocadq commented on app/Http/Requests/DonationRequestFormRequest.php
> +    public function messages()
```suggestion
    }
    
    public function messages()
```

2022-02-23 13:50 UTC, nicocadq commented on app/Http/Requests/DonationRequestFormRequest.php
> +            // 'message' => 'Algo ha salido mal',
```suggestion
```

2022-02-23 13:50 UTC, nicocadq commented on app/Http/Requests/LogInFormRequest.php
> +            // 'message' => 'Algo ha salido mal',
```suggestion
```

2022-02-23 13:50 UTC, nicocadq commented on app/Http/Requests/LogInFormRequest.php
> +            'password.required' => 'El campo es requerido',
Try to be consistent
```suggestion
            'email.required' => 'Este campo es requerido',
            'password.required' => 'Este campo es requerido',
```

2022-02-23 13:50 UTC, nicocadq commented on app/Http/Requests/PetitionStoreFormRequest.php
> +            'subject.required' => 'El campo del Titulo es requerido',
Same here

```suggestion
    }
    
    public function messages()
    {
        return [
            'subject.required' => 'El Titulo es requerido',
```

2022-02-23 13:50 UTC, nicocadq commented on app/Http/Requests/RegisterFormRequest.php
> +        ];
```suggestion
            'email.unique' => 'Este email ya existe',
            'email.required' => 'El email es requerido',
            'email.email' => 'Ingrese un email valido',
            'name.required' => 'El nombre es requerido',
            'password.required' => 'La contraseña es requerida',
        ];
```

2022-02-23 13:50 UTC, nicocadq commented on app/Http/Requests/StoreDonationFormRequest.php
> +            // 'message' => 'Algo ha salido mal',
```suggestion
```

2022-02-23 13:50 UTC, nicocadq commented on app/Http/Requests/StoreDonationFormRequest.php
> +            'description.required' => 'El campo de Descripcion es requerido',
```suggestion
            'name.required' => 'El Titulo es requerido',
            'description.required' => 'La Descripcion es requerida',
```

2022-02-23 13:50 UTC, nicocadq commented on app/Http/Requests/StoreDonationFormRequest.php
> +            'image.max' => 'El maximo de la imagen es de 5Mb',
```suggestion
            'image.max' => 'El tamaño maximo de la imagen puede ser de hasta 5Mb',
```

2022-02-23 13:50 UTC, nicocadq commented on app/Http/Requests/UpdateFormRequest.php
> +            'phone.numeric' => 'Porfavor indique un numero',
```suggestion
            'email.required' => 'El email es requerido',
            'password.required' => 'La contraseña es requerida',
            'name.required' => 'El nombre es requerido',
            'name.string' => 'Indique un nombre valido',
            'phone.numeric' => 'Porfavor indique un número',
```

2022-02-23 13:50 UTC, nicocadq commented on app/Http/Requests/UpdateFormRequest.php
> +            'image.max' => 'El maximo de la imagen es de 1Mb',
```suggestion
            'image.image' => 'No se pudo subir la imagen',
            'image.max' => 'El tamaño maximo de la imagen puede ser de hasta 1Mb',
```

2022-02-24 01:09 UTC, alejandroGonGon commented on app/Http/Requests/UpdateFormRequest.php
> +            'image.max' => 'El maximo de la imagen es de 1Mb',
Done

2022-02-24 01:09 UTC, alejandroGonGon commented on app/Http/Requests/UpdateFormRequest.php
> +            'phone.numeric' => 'Porfavor indique un numero',
Done

2022-02-24 01:09 UTC, alejandroGonGon commented on app/Http/Requests/StoreDonationFormRequest.php
> +            'image.max' => 'El maximo de la imagen es de 5Mb',
Done

2022-02-24 01:09 UTC, alejandroGonGon commented on app/Http/Requests/StoreDonationFormRequest.php
> +            'description.required' => 'El campo de Descripcion es requerido',
Done

2022-02-24 11:31 UTC, rubenderigo requested changes

2022-02-24 11:31 UTC, rubenderigo commented on app/Http/Requests/DonationRequestFormRequest.php
> +            'password.string' => 'Ingrese una Razon con caracteres validos',
```suggestion
            'password.string' => 'Ingrese una razón con caracteres válidos',
```

2022-02-24 11:31 UTC, rubenderigo commented on app/Http/Requests/PetitionStoreFormRequest.php
> +            'subject.required' => 'El Titulo es requerido',
```suggestion
            'subject.required' => 'El titulo es requerido',
```

2022-02-24 11:31 UTC, rubenderigo commented on app/Http/Requests/StoreDonationFormRequest.php
> +            'name.required' => 'El Titulo es requerido',
```suggestion
            'name.required' => 'El titulo es requerido',
```

2022-02-24 11:31 UTC, rubenderigo commented on app/Http/Requests/StoreDonationFormRequest.php
> +            'description.required' => 'La Descripcion es requerida',
```suggestion
            'description.required' => 'La descripción es requerida',
```

2022-02-24 11:31 UTC, rubenderigo commented on app/Http/Requests/StoreDonationFormRequest.php
> +            'image.image' => 'Se necesita una Imagen valida',
```suggestion
            'image.image' => 'Se necesita una imagen valida',
```

2022-02-24 11:31 UTC, rubenderigo commented on app/Http/Requests/StoreDonationFormRequest.php
> +            'image.max' => 'El tamaño maximo de la imagen puede ser de hasta 5Mb',
```suggestion
            'image.max' => 'El tamaño máximo de la imagen puede ser de hasta 5Mb',
```

2022-02-24 11:31 UTC, rubenderigo commented on app/Http/Requests/UpdateFormRequest.php
> +            'phone.numeric' => 'Porfavor indique un número',
```suggestion
            'phone.numeric' => 'Por favor indique un número',
```

2022-02-24 11:31 UTC, rubenderigo commented on app/Http/Requests/UpdateFormRequest.php
> +            'about_me.string' => 'Porfavor indique solo texto',
```suggestion
            'about_me.string' => 'Por favor indique solo texto',
```

2022-02-24 11:31 UTC, rubenderigo commented on app/Http/Requests/UpdateFormRequest.php
> +            'image.max' => 'El tamaño maximo de la imagen puede ser de hasta 1Mb',
```suggestion
            'image.max' => 'El tamaño máximo de la imagen puede ser de hasta 1Mb',
```

2022-02-25 01:49 UTC, merged