Fixing the URL that appear in the buttons of the Emails
paintedbirds/hoydonamos-api pull request #22
Opened 2022-03-25 13:18 UTC by alejandroGonGon

**About**

When an email is send it they where with the Amazon URL, so I changed to .env variables for future changes and adaptability.

2022-03-28 12:27 UTC, rubenderigo approved these changes
LGTM

2022-03-30 19:13 UTC, alejandroGonGon commented
> LGTM

Can you approve my "Suggested change"

2022-04-03 02:41 UTC, nicocadq requested changes

2022-04-03 02:41 UTC, nicocadq commented on resources/views/emails/petitionCreated.blade.php
> +<table border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate;width:144px;line-height:100%;"><tbody><tr><td align="center" bgcolor="#73b8b2" style="border:none;border-radius:8px 8
```suggestion
<table border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate;width:144px;line-height:100%;"><tbody><tr><td align="center" bgcolor="#73b8b2" style="border:none;border-radius:8px 8px 8px 8px;cursor:auto;mso-padding-alt:12px 0px 12px 0px;background:#73b8b2;" valign="middle"> <a href="{{ env('URL_WEB') }}/peticiones/?petition_id={{$petitionData['id']}}" style="display:inline-block;width:144px;background:#73b8b2;color:#ffffff;font-family:Roboto,Arial,sans-serif;font-size:13px;font-weight:normal;line-height:100%;margin:0;text-decoration:none;text-transform:none;padding:12px 0px 12px 0px;mso-padding-alt:0;border-radius:8px 8px 8px 8px;" target="_blank"> <span style="mso-line-height-rule:exactly;font-size:14px;font-family:Roboto,Arial,sans-serif;font-weight:700;color:#ffffff;line-height:16px;">VER SOLICITUD</span></a>
```

2022-04-03 07:25 UTC, nicocadq approved these changes

2022-04-03 15:42 UTC, nicocadq approved these changes

2022-04-04 18:21 UTC, merged